feature: github issue form
leonsteinhaeuser/project-beta-automations pull request #51
Opened 2022-08-19 21:45 UTC by leonsteinhaeuser

This PR removes Markdown issue templates and adds GitHub issue forms.

Closes: #48

2022-08-20 01:07 UTC, scarf005 requested changes
Very nice! however adding `questions` issue might be confusing over `Q&A` in discussions tab. i'd suggest adding a link to guide them to discussions.

2022-08-23 19:57 UTC, leonsteinhaeuser commented on .github/ISSUE_TEMPLATE/question.yml
> +      description: A clear and concise description of what the question is about.
Good point. I will add your change.

2022-08-23 21:36 UTC, scarf005 approved these changes
great!
maybe could you also remove `.github/ISSUE_TEMPLATE/question.yml` before merging since now it's empty?

2022-08-23 22:22 UTC, leonsteinhaeuser commented
> great! maybe could you also remove `.github/ISSUE_TEMPLATE/question.yml` before merging since now it's empty?

That makes sense. I used the GitHub merge buttons and it seems that one of the changes did not delete the question template. I have now done this by hand.

2022-08-23 23:20 UTC, scarf005 commented
> At least 1 approving review is required by reviewers with write access. 

since my review approval doesn't count (no write access), you could safely merge with administer rights .

2022-08-24 09:57 UTC, merged